### ISSUE TITLE
Error svnversion: not found

### ISSUE THREAD

**Issue by maccagnan** [be1/qliquidsfz#3]
Devuan Daedalus
libliquid-dev:amd64 (1.5.0-2)
qttools5-dev-tools (5.15.8-2)

When issuing the command:
$qmake -config release
sh: 1: svnversion: not found

Am I missing something?

**Comment by be1** [comment]
Thanks for reporting the issue.
This should be fixed with commit https://github.com/be1/qliquidsfz/commit/caecaa6e442957d909e85c5c2d24d18d7c075a3d

**Comment by maccagnan** [comment]
Installing subversion solved the problem.
